ai:
    introduce: 你好, 这是自我介绍
    prompt: 我目前在寻求兼职、顾问或项目合作机会，偏好远程/线上模式。%s,我期望的方向是【%s】,目前我需要投递的职位是【%s】,这个职位的要求是【%s】,请判断这个职位是否与我的人工智能、博士科研背景、或教学指导能力相关。只要是兼职/项目制，且内容沾边（例如科研、教学、写作、咨询、技术支持等），不强制要求线下办公，就请帮我写一个给对方打招呼的文本发给我; 若确实完全无关再返回false (判断标准非常宽松，有任何技能或知识上的关联即可)，注意只返回所需内容, 文字不超过20词, 突出我的专业背景与问题解决能力及职位匹配度, 我自己写的招呼语是：【%s】, 必须严格按照我的招呼语输出 , 禁止加任何多余词汇
boss:
    cityCode:
        - "1.011901e+08"
        - "1.010201e+08"
        - "1.012201e+08"
        - "1.012801e+08"
    customCityCode: {}
    deadStatus:
        - 2周内活跃
        - 本月活跃
    degree:
        - "203"
    enableAI: true
    expectedSalary:
        - 10
        - 60
    experience:
        - "105"
    filterDeadHR: true
    industry:
        - "0"
    interval: 2
    jobType: "1903"
    keywords:
        - 智能体开发
        - go
        - java
        - leo
    max: 15
    salary: "0"
    sayHi: 您好，我对这份工作非常感兴趣，希望可以有机会与您进一步沟通。
    scale:
        - "302"
    sendImgResume: false
    stage:
        - "0"
    waitTime: 4
bot:
    is_send: true
    template: |-
        ## 新投递成功
        - 岗位：{{jobLink}}
        - 公司：{{companyName}}
        - 城市/经验：{{jobArea}}
        - 薪资：{{salary}}
        - 招呼语：{{greeting}}
        - 状态：{{status}}
